# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MashStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Brew')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('water', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=b'recipe', chained_model_field=b'recipe', on_delete=django.db.models.deletion.CASCADE, to='recipes.Water')),
            ],
        ),
    ]
