# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BoilStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MashIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MashStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Brew')),
            ],
        ),
        migrations.AddField(
            model_name='mashingredient',
            name='mash_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.MashStep'),
        ),
        migrations.AddField(
            model_name='boilstep',
            name='brew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Brew'),
        ),
        migrations.AddField(
            model_name='boilingredient',
            name='mash_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.MashStep'),
        ),
    ]
