# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_hop_malt_water'),
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 3, 9, 2, 46, 850708, tzinfo=utc), verbose_name=b'finished date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brew',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
